### ISSUE TITLE
Where to get released jar library?

### ISSUE THREAD

**Issue by xzllxls** [postspectacular/toxiclibs#14]
Excuse me. 
The toxiclibs official website: http://toxiclibs.org/ may not be accessed normally.
Where to get the entire released jar library?

**Comment by postspectacular** [comment]
Hi, there's a link to the zip file containing all the library jars on the repo homepage, or directly from here:

https://github.com/postspectacular/toxiclibs/releases

👍

**Comment by postspectacular** [comment]
Ps. After 15 years, the toxiclibs website is now defunkt, also see announcement here:

https://twitter.com/toxi/status/1529018996128899072

**Comment by GoToLoop** [comment]
Could you make the "defunct" site available as a GitHub Page then please?

**Comment by postspectacular** [comment]
Sorry, not really! I've got a partial backup, but the original site was in Wordpress and it's currently v. low priority for me to convert & restore it as a static site. It's on the todo list, but don't expect it anytime soon.

Additionally, there's always the Wayback Machine:

https://web.archive.org/web/20120307130939/http://toxiclibs.org/
