### ISSUE TITLE
Spline2D source does not include full implementation

### ISSUE THREAD

**Issue by gncgnc** [postspectacular/toxiclibs#5]
The methods used in the examples are not in the source code posted here. Perhaps an older version is displayed here? For example, the `computeVertices` method of Spline2D is nowhere to be found in the code while being crucial to the class. I would appreciate the full source as I need some more details on the implementation. 

I'm trying to figure out how exactly to set control points on the ends of splines to make a "spline loop". The `delta` array holds the control point data presumably, but I'm not exactly sure what to set as the deltas at the endpoints. This is why I need to see the implemention; it's not clear to me what the `delta` array holds even after looking at the data it contains.

**Comment by postspectacular** [comment]
It's not that there're missing implementations, but that some of the methods have been renamed. `Spline2D/3D.computeVertices()` being one of them and is now called `.toLineStrip2D/3D()`...

https://github.com/postspectacular/toxiclibs/blob/master/src.core/toxi/geom/Spline2D.java#L244

Hth!

**Comment by gncgnc** [comment]
I see, thank you for the response. I was following from the docs at http://toxiclibs.org/docs/core/ where the old method names persist. I happened to have an old version installed which I believe I downloaded from the same site. So the docs on the site and the download were in sync I suppose.
